# -*- coding: utf-8 -*-
"""Copy of hierarchical_clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cu_UFPqj_OeeeMaB2zypv1YZINtyn2zZ

# Hierarchical Clustering

## Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Mall_Customers.csv')
x = dataset.iloc[:, [3, 4]].values

"""## Using the dendrogram to find the optimal number of clusters"""

import scipy.cluster.hierarchy as sch
dendrogram = sch.dendrogram(sch.linkage(x, method='ward'))
plt.title('Dendrogram')
plt.xlabel('Customers')
plt.ylabel('Euclidean Distance')
plt.show()

"""## Training the Hierarchical Clustering model on the dataset"""

from sklearn.cluster import AgglomerativeClustering
hc = AgglomerativeClustering(n_clusters=5)
y_hc = hc.fit_predict(x)

"""## Visualising the clusters"""

plt.scatter(x[y_hc==0, 0], x[y_hc==0, 1], c ='red', s=100, label='Cluster 1')
plt.scatter(x[y_hc==1, 0], x[y_hc==1, 1], c ='blue', s=100, label='Cluster 2')
plt.scatter(x[y_hc==2, 0], x[y_hc==2, 1], c ='green', s=100, label='Cluster 3')
plt.scatter(x[y_hc==3, 0], x[y_hc==3, 1], c ='cyan', s=100, label='Cluster 4')
plt.scatter(x[y_hc==4, 0], x[y_hc==4, 1], c ='magenta', s=100, label='Cluster 5')
plt.title('Clusters of customers')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.legend()
plt.show()